import type { LogicLayoutPart } from "./redstoneLogicLayouts";

// Block positions transcribed from the compact XOR reference image.
export const COMPACT_XOR_LAYOUT: LogicLayoutPart[] = [
  { layer: 1, kind: "lever", x: 6, z: 0, facing: "east", mount: "wall", powered: false, input: "A" },
  { layer: 1, kind: "lever", x: 6, z: 4, facing: "east", mount: "wall", powered: false, input: "B" },
  { layer: 0, kind: "stone", x: 6, z: 0 },
  { layer: 0, kind: "stone", x: 6, z: 4 },
  { layer: 1, kind: "lamp", x: 6, z: 0, label: "A" },
  { layer: 1, kind: "lamp", x: 6, z: 4, label: "B" },
  { layer: 0, kind: "stone", x: 3, z: 0 },
  { layer: 0, kind: "stone", x: 3, z: 4 },
  { layer: 0, kind: "stone", x: 4, z: 2 },
  { layer: 1, kind: "stone", x: 4, z: 2 },
  { layer: 2, kind: "dust", x: 4, z: 2 },
  { layer: 0, kind: "stone", x: 5, z: 0 },
  { layer: 0, kind: "stone", x: 4, z: 0 },
  { layer: 0, kind: "stone", x: 4, z: 1 },
  { layer: 0, kind: "stone", x: 5, z: 4 },
  { layer: 0, kind: "stone", x: 4, z: 4 },
  { layer: 0, kind: "stone", x: 4, z: 3 },
  { layer: 0, kind: "stone", x: 2, z: 0 },
  { layer: 0, kind: "stone", x: 1, z: 0 },
  { layer: 0, kind: "stone", x: 1, z: 2 },
  { layer: 0, kind: "stone", x: 2, z: 4 },
  { layer: 0, kind: "stone", x: 1, z: 4 },
  { layer: 0, kind: "stone", x: 0, z: 2 },
  { layer: 1, kind: "dust", x: 5, z: 0 },
  { layer: 1, kind: "dust", x: 4, z: 0 },
  { layer: 1, kind: "dust", x: 4, z: 1 },
  { layer: 1, kind: "dust", x: 5, z: 4 },
  { layer: 1, kind: "dust", x: 4, z: 4 },
  { layer: 1, kind: "dust", x: 4, z: 3 },
  { layer: 1, kind: "torch", x: 3, z: 0 },
  { layer: 1, kind: "torch", x: 3, z: 4 },
  { layer: 1, kind: "dust", x: 2, z: 0 },
  { layer: 1, kind: "dust", x: 1, z: 0 },
  { layer: 1, kind: "dust", x: 1, z: 2 },
  { layer: 1, kind: "dust", x: 2, z: 4 },
  { layer: 1, kind: "dust", x: 1, z: 4 },
  { layer: 1, kind: "lamp", x: 0, z: 2, label: "OUT" },
  { layer: 0, kind: "stone", x: 1, z: 1 },
  { layer: 0, kind: "stone", x: 1, z: 3 },
  { layer: 1, kind: "dust", x: 1, z: 1 },
  { layer: 1, kind: "dust", x: 1, z: 3 },
];
